## DAY 24
### EXERCISES

In [3]:
#importing numpy and rename it to np
import numpy as np
print('numpy:', np.__version__)
directories = dir(np)
for direc in directories:
	print(direc)

numpy: 1.24.2
ALLOW_THREADS
AxisError
BUFSIZE
CLIP
ComplexWarning
DataSource
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
ModuleDeprecationWarning
NAN
NINF
NZERO
NaN
PINF
PZERO
RAISE
RankWarning
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
Tester
TooHardError
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
VisibleDeprecationWarning
WRAP
_CopyMode
_NoValue
_UFUNC_API
__NUMPY_SETUP__
__all__
__builtins__
__cached__
__config__
__deprecated_attrs__
__dir__
__doc__
__expired_functions__
__file__
__former_attrs__
__future_scalars__
__getattr__
__git_version__
__loader__
__name__
__package__
__path__
__spec__
__version__
_add_newdoc_ufunc
_builtins
_distributor_init
_financial_names
_get_promotion_state
_globals
_int_extended_msg
_mat
_no_nep50_warning
_pyinstaller_hooks_dir
_pytesttester
_set_promotion_

In [17]:
python_list = [1,2,3,4,5]
print('Type:', type (python_list))
print(python_list)
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
print(two_dimensional_list)


numpy_array_from_list = np.array(python_list)
numpy_ = np.array(two_dimensional_list)
print(type(numpy_array_from_list))
print(numpy_array_from_list)


Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [16]:
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)

numpy_bool_array = np.array([0, 1, -1, 0, 0,], dtype=bool)
print(numpy_bool_array)

[1. 2. 3. 4. 5.]
[False  True  True False False]


In [18]:
print(type(numpy_))
print(numpy_)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]
