## DAY 24
### EXERCISES

### Importing Numpy

In [45]:
#importing numpy and rename it to np
import numpy as np
print('numpy:', np.__version__)
print(dir(np))

numpy: 1.24.2
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec_

### Creating int numpy arrays


In [46]:
python_list = [1,2,3,4,5]
print('Type:', type (python_list))
print(python_list)
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
print(two_dimensional_list)


numpy_array_from_list = np.array(python_list)
numpy_two = np.array(two_dimensional_list)
print(type(numpy_array_from_list))
print(numpy_array_from_list)


Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


### Creating float/boolean numpy arrays


In [47]:
numpy_array_from_list2 = np.array(python_list, dtype=float)
print(numpy_array_from_list2)

numpy_bool_array = np.array([0, 1, -1, 0, 0,], dtype=bool)
print(numpy_bool_array)

[1. 2. 3. 4. 5.]
[False  True  True False False]


### Creating multidimensional array using numpy


In [48]:
print(type(numpy_two))
print(numpy_two)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Converting numpy array to list


In [49]:
np_to_list = numpy_array_from_list.tolist()
print(type(np_to_list))
print('one dimetional array: ', np_to_list)
print('two dimetional array: ', numpy_two.tolist())


<class 'list'>
one dimetional array:  [1, 2, 3, 4, 5]
two dimetional array:  [[0, 1, 2], [3, 4, 5], [6, 7, 8]]


### Creating numpy array from tuple


In [50]:
# numpy array from tuple
# Creating tuple in python
python_tuple = (1,2,3,4,5)
print(type(python_tuple))
print('python tuple: ', python_tuple)

numpy_array_from_tuple = np.array(python_tuple)
print(type(numpy_array_from_tuple))
print('numpy array from tuple: ', numpy_array_from_tuple)

<class 'tuple'>
python tuple:  (1, 2, 3, 4, 5)
<class 'numpy.ndarray'>
numpy array from tuple:  [1 2 3 4 5]


### Shape of numpy array


In [51]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
print(numpy_two)
print('shape of numpy_two_dimensional_list: ', numpy_two.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
        [4,5,6,7],
        [8,9,10, 11]])
print('three_by_four_array: ',three_by_four_array.shape)

[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
three_by_four_array:  (3, 4)


### Data type of numpy array


In [52]:
int_list = [-3, -2, -1, 0, 1, 2,3]
int_array = np.array(int_list)
float_array = np.array(int_list, dtype=float)
str_array = np.array(int_list, dtype=str)

print(int_array)
print(int_array.dtype)
print(float_array)
print(float_array.dtype)
print(str_array)
print(str_array.dtype)

[-3 -2 -1  0  1  2  3]
int32
[-3. -2. -1.  0.  1.  2.  3.]
float64
['-3' '-2' '-1' '0' '1' '2' '3']
<U2


### Size of a numpy array

In [53]:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
two_dimensional_list = np.array([[0, 1, 2],
                              	 [3, 4, 5],
                                 [6, 7, 8]])

print('The size:', numpy_array_from_list.size) # 5
print('The size:', two_dimensional_list.size)  # 3

The size: 5
The size: 9


Mathematical Operation using numpy
NumPy array is not like exactly like python list. To do mathematical operation in Python list we have to loop through the items but numpy can allow to do any mathematical operation without looping. Mathematical Operation:

Addition (+)
Subtraction (-)<br>
Multiplication (*)
Division (/)<br>
Modules (%)
 Floor Division (//)
 Exponential (**)

### Addition

In [54]:
# Mathematical Operation
# Addition
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_plus_original = numpy_array_from_list  + 10
print(ten_plus_original)

original array:  [1 2 3 4 5]
[11 12 13 14 15]


### Subtraction

In [55]:
#Subtraction
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_minus_original = numpy_array_from_list  - 10
print(ten_minus_original)

original array:  [1 2 3 4 5]
[-9 -8 -7 -6 -5]


### Multiplication

In [56]:
# Multiplication
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list * 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[10 20 30 40 50]


### Division

In [57]:
#Division
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list / 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


### Modulus

In [58]:
# Modulus; Finding the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list % 3
print(ten_times_original)

original array:  [1 2 3 4 5]
[1 2 0 1 2]


### Floor division

In [59]:
# Floor division: the division result without the remainder
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list // 10
print(ten_times_original)

original array:  [1 2 3 4 5]
[0 0 0 0 0]


### Exponential

In [60]:
# Exponential is finding some number the power of another:
numpy_array_from_list = np.array([1, 2, 3, 4, 5])
print('original array: ', numpy_array_from_list)
ten_times_original = numpy_array_from_list  ** 2
print(ten_times_original)

original array:  [1 2 3 4 5]
[ 1  4  9 16 25]


### Checking data types

In [61]:
#Int,  Float numbers
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int32
float64
bool


### Converting types
#### We can convert the data types of numpy array
1. Int to Float
2. float to int
3. Int ot boolean
4. Int to str

In [66]:
numpy_int_to_float = np.array([1,2,3,4], dtype = 'float')
print(numpy_int_to_float)

numpy_float_to_int = np.array([1., 2., 3., 4.], dtype = 'int')
print(numpy_float_to_int)


numpy_int_to_bool = np.array([-3, -2, 0, 1,2,3], dtype='bool')
print(numpy_int_to_bool)

numpy_float_arr.astype('int').astype('str')


[1. 2. 3. 4.]
[1 2 3 4]
[ True  True False  True  True  True]


array(['1', '2', '3'], dtype='<U11')

### Multi-dimensional Arrays

In [67]:
# 2 Dimension Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int32


### Getting items from a numpy array

In [71]:
# 2 Dimension Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)

print('__'*50, '\n')
    
first_column= two_dimension_array[:,0]
second_column = two_dimension_array[:,1]
third_column = two_dimension_array[:,2]
print('First column:', first_column)
print('Second column:', second_column)
print('Third column: ', third_column)
print(two_dimension_array)

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]
____________________________________________________________________________________________________ 

First column: [1 4 7]
Second column: [2 5 8]
Third column:  [3 6 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Slicing Numpy array
#### Slicing in numpy is similar to slicing in python list

In [72]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_two_rows_and_columns = two_dimension_array[0:2, 0:2]
print(first_two_rows_and_columns)

[[1 2]
 [4 5]]


### Reverse the row and column positions

In [89]:
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(f'Before Reversing:\n{two_dimension_array}')
print(f'After reversing:\n{two_dimension_array[::-1,::-1]}')

Before Reversing:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After reversing:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### How to represent missing values ?

In [90]:
print(two_dimension_array)
two_dimension_array[1,1] = 50
two_dimension_array[1,2] = 40
print(two_dimension_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 50 40]
 [ 7  8  9]]


In [95]:
# Numpy Zeroes
# numpy.zeros(shape, dtype=float, order='C')
numpy_zeros = np.zeros((3,3), dtype = int, order="C" )
numpy_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [99]:
# Numpy ones
# numpy.ones(shape, dtype=float, order='C')
numpy_ones = np.ones((3,3), dtype = int, order="C" )
numpy_ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [101]:
twoes = numpy_ones * 2
twoes

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [106]:
# Reshape
# numpy.reshape(), numpy.flatten()
first_shape  = np.array([(1,2,3), (4,5,6)])
print(first_shape)
reshaped = first_shape.reshape(3,2)
print(reshaped)

flattened = reshaped.flatten()
flattened

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([1, 2, 3, 4, 5, 6])

In [107]:
## Horitzontal Stack
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

print(np_list_one + np_list_two)

print('Horizontal Append:', np.hstack((np_list_one, np_list_two)))

## Vertical Stack
print('Vertical Append:', np.vstack((np_list_one, np_list_two)))

[5 7 9]
Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]
